export const API_ERRORS = {
  UNAUTHORIZED: "Потрібна авторизація",
  FORBIDDEN: "Недостатньо прав",
  NOT_FOUND: "Не знайдено",
  CAMPAIGN_NOT_FOUND: "Кампанію не знайдено",
  CHARACTER_NOT_FOUND: "Персонажа не знайдено",
  RACE_NOT_FOUND: "Расу не знайдено",
  SKILL_NOT_FOUND: "Навик не знайдено",
  MEMBER_NOT_FOUND: "Учасника не знайдено",
  INVALID_BODY: "Некоректні дані запиту",
  INVALID_QUERY: "Некоректні параметри запиту",
  INVALID_JSON: "Некоректний JSON у тілі запиту",
  TOO_MANY_REQUESTS: "Забагато запитів, спробуйте трохи згодом",
  ABILITY_TOO_MANY_TARGETS: "Забагато цілей для цього вміння",
  BONUS_TARGET_MUST_BE_DEAD: "Ціль має бути мертвою",
  SPELL_TOO_MANY_TARGETS: "Забагато цілей для цього закляття",
  INTERNAL: "Внутрішня помилка сервера",
  FOREIGN_KEY: "Пов'язаний запис не існує",
  CAMPAIGN_NOT_ACTIVE: "Кампанія не активна",
  ALREADY_MEMBER: "Ви вже є учасником цієї кампанії",
  CANNOT_REMOVE_DM: "DM не можна видалити з кампанії",
  UNKNOWN_OWNER_KIND: "Невідомий тип власника",
  MISSING_PUSHER_PARAMS: "Потрібні socket_id і channel_name",
} as const;
